### ISSUE TITLE
VS 7.1.0 fails to load on Spigot 1.8.8

### ISSUE THREAD

**Issue by snhnry** [TVPT/VoxelGunsmith#14]
Using build #418 and latest Spigot 1.8.8 gives this error on server start: 

```
Could not load 'plugins/VoxelSniper-7.1.0-SNAPSHOT.jar' in folder 'plugins'

Console 01/31/2016 17:21:55 17:21:55
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:162) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.util.zip.ZipException: error in opening zip file
at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_60]
at java.util.zip.ZipFile.(ZipFile.java:219) ~[?:1.8.0_60]
at java.util.zip.ZipFile.(ZipFile.java:149) ~[?:1.8.0_60]
at java.util.jar.JarFile.(JarFile.java:166) ~[?:1.8.0_60]
at java.util.jar.JarFile.(JarFile.java:130) ~[?:1.8.0_60]
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:150) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
... 5 more
```

It's also impossible to open the jar file as an archive in windows to view the contents.

**Comment by gabizou** [comment]
Try using the `all` jar from jenkins.

**Comment by snhnry** [comment]
Tried both, errors are identical.

**Comment by Mumfrey** [comment]
We corrected an issue with the jenkins server, try re-downloading the jar.

**Comment by snhnry** [comment]
Confirmed working, thank you both for the prompt responses.
